name: Choice input behavior
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      logical:
        description: 'True to print to logical'
        required: true
        type: boolean

jobs:
  print-values:
    runs-on: ubuntu-latest
    steps:
      - name: Print logLevel value
        run: echo  "logLevel value is ${{ inputs.logLevel }}"
      - name: Print logLevel value from context
        run: echo  "logLevel value is ${{ github.event.inputs.logLevel }}"
      - name: Print logical value
        run: echo  "logical value is ${{ inputs.logical }}"
      - name: Print logical value from context
        run: echo  "logical value is ${{ github.event.inputs.logical }}"
  print-values-workflow:
    uses: ./.github/workflows/choice-input-reusable.yaml
    permissions:
      packages: write
