name: Print GitHub context

on:
  pull_request:
    types: [ready_for_review, opened, reopened, edited, synchronize, labeled]
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  view:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job ID: ${{ github.job }}"
      - run: echo "${{ toJSON(github) }}"
