name: Verify different triggers and events

on:
  pull_request:
    types: [ready_for_review, opened, reopened, edited, synchronize, labeled]
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'

jobs:
  initialize:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' ||
      (
        github.event.pull_request.draft == false ||
        (
          github.event.action == 'labeled' &&
          github.event.label.name == 'runtest'
        )
      )
    steps:
      - name: Remove runtest if exists
        continue-on-error: true  # Ignore this step if the workflow didn't get triggered from a PR.
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            ${{ github.event.pull_request.base.repo.url }}/issues/${{ github.event.number }}/labels/runtest
      - run: echo "PR initialized"
  successor:
    runs-on: ubuntu-latest
    needs: [ initialize ]
    steps:
      - run: echo "Successor step"
