name: remove-stale-issues

on:
  workflow_dispatch:

jobs:
  remove-stale-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Inform run
        run: |
          set -x
          echo "Removing stale issues started"
      - uses: actions/stale@v5
